-- 071: полный явный слой грантов (baseline из production).
--
-- Контекст (см. 070 и docs/database.md): новые стеки Supabase не выдают
-- app-ролям автоматических грантов на объекты из миграций. Действующий
-- production создан на старых дефолтах, и его фактическая модель доступа —
-- результат legacy-грантов + всех накопленных REVOKE. Этот файл — её
-- механический перенос: снят с production (supabase db dump, июль 2026) фильтром
-- «только authenticated/service_role, только public», применён поверх
-- любых дефолтов. В production каждый GRANT — no-op.
--
-- Решения:
--  * anon НЕ получает ничего: гостевые потоки идут через Edge Functions
--    (service_role); legacy anon-гранты прода не переносятся.
--  * Колоночные гранты staff сохранены как в 001: pin_hash недоступен.
--  * В конце — повтор жёстких REVOKE (op_log, staff_sessions, order_counters,
--    guests, loyalty_events): hardened-дефолт даёт authenticated
--    TRUNCATE/TRIGGER даже без DML, эти таблицы должны быть закрыты целиком.
--  * Новые объекты в будущих миграциях обязаны выдавать явные GRANT сами.

-- ── Жёстко закрытые таблицы: сначала снять hardened-остатки (TRUNCATE/
-- TRIGGER/…), ниже гранты вернут ровно то, что есть в production (например,
-- точечные колоночные права guests/loyalty_events для лояльности). ──
REVOKE ALL ON op_log         FROM anon, authenticated, public;
REVOKE ALL ON staff_sessions FROM anon, authenticated, public;
REVOKE ALL ON order_counters FROM anon, authenticated, public;
REVOKE ALL ON guests         FROM anon, authenticated, public;
REVOKE ALL ON loyalty_events FROM anon, authenticated, public;

-- ── Схема ──
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

-- ── Таблицы (75 строк, срез production) ──
GRANT ALL ON TABLE "public"."cash_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."cash_movements" TO "service_role";
GRANT ALL ON TABLE "public"."devices" TO "authenticated";
GRANT ALL ON TABLE "public"."devices" TO "service_role";
GRANT ALL ON TABLE "public"."guests" TO "service_role";
GRANT ALL ON TABLE "public"."item_variants" TO "authenticated";
GRANT ALL ON TABLE "public"."item_variants" TO "service_role";
GRANT ALL ON TABLE "public"."locations" TO "service_role";
GRANT ALL ON TABLE "public"."loyalty_events" TO "service_role";
GRANT ALL ON TABLE "public"."menu_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_categories" TO "service_role";
GRANT ALL ON TABLE "public"."menu_item_modifier_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_item_modifier_groups" TO "service_role";
GRANT ALL ON TABLE "public"."menu_items" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_items" TO "service_role";
GRANT ALL ON TABLE "public"."modifier_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."modifier_groups" TO "service_role";
GRANT ALL ON TABLE "public"."modifiers" TO "authenticated";
GRANT ALL ON TABLE "public"."modifiers" TO "service_role";
GRANT ALL ON TABLE "public"."online_orders" TO "service_role";
GRANT ALL ON TABLE "public"."op_log" TO "service_role";
GRANT ALL ON TABLE "public"."order_counters" TO "service_role";
GRANT ALL ON TABLE "public"."order_item_modifiers" TO "service_role";
GRANT ALL ON TABLE "public"."order_items" TO "service_role";
GRANT ALL ON TABLE "public"."orders" TO "service_role";
GRANT ALL ON TABLE "public"."orgs" TO "authenticated";
GRANT ALL ON TABLE "public"."orgs" TO "service_role";
GRANT ALL ON TABLE "public"."payments" TO "service_role";
GRANT ALL ON TABLE "public"."receipt_counters" TO "authenticated";
GRANT ALL ON TABLE "public"."receipt_counters" TO "service_role";
GRANT ALL ON TABLE "public"."refund_counters" TO "authenticated";
GRANT ALL ON TABLE "public"."refund_counters" TO "service_role";
GRANT ALL ON TABLE "public"."refunds" TO "service_role";
GRANT ALL ON TABLE "public"."reservations" TO "service_role";
GRANT ALL ON TABLE "public"."shifts" TO "service_role";
GRANT ALL ON TABLE "public"."staff" TO "service_role";
GRANT ALL ON TABLE "public"."staff_sessions" TO "service_role";
GRANT ALL ON TABLE "public"."stations" TO "authenticated";
GRANT ALL ON TABLE "public"."stations" TO "service_role";
GRANT ALL ON TABLE "public"."stock_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."stock_movements" TO "service_role";
GRANT ALL ON TABLE "public"."supply_items" TO "authenticated";
GRANT ALL ON TABLE "public"."supply_items" TO "service_role";
GRANT ALL ON TABLE "public"."table_zones" TO "authenticated";
GRANT ALL ON TABLE "public"."table_zones" TO "service_role";
GRANT ALL ON TABLE "public"."tables" TO "authenticated";
GRANT ALL ON TABLE "public"."tables" TO "service_role";
GRANT ALL ON TABLE "public"."time_entries" TO "service_role";
GRANT ALL ON TABLE "public"."waste_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."waste_entries" TO "service_role";
GRANT ALL ON TABLE "public"."z_counters" TO "authenticated";
GRANT ALL ON TABLE "public"."z_counters" TO "service_role";
GRANT INSERT("name"),UPDATE("name") ON TABLE "public"."guests" TO "authenticated";
GRANT INSERT("org_id") ON TABLE "public"."guests" TO "authenticated";
GRANT INSERT("phone"),UPDATE("phone") ON TABLE "public"."guests" TO "authenticated";
GRANT REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT ON TABLE "public"."guests" TO "authenticated";
GRANT SELECT ON TABLE "public"."loyalty_events" TO "authenticated";
GRANT SELECT("created_at") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT("id") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT("is_active") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT("location_id") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT("name") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT("org_id") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT("role") ON TABLE "public"."staff" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."locations" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."online_orders" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."order_item_modifiers" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."order_items" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."orders" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."payments" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."refunds" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."reservations" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."shifts" TO "authenticated";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."time_entries" TO "authenticated";

-- ── Функции (541 строка, срез production) ──
GRANT ALL ON FUNCTION "public"."_pick_tables"("p_location_id" "uuid", "p_party" integer, "p_at" timestamp with time zone, "p_dur_min" integer, "p_buffer" integer, "p_combine" boolean, "p_exclude" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."_pick_tables"("p_location_id" "uuid", "p_party" integer, "p_at" timestamp with time zone, "p_dur_min" integer, "p_buffer" integer, "p_combine" boolean, "p_exclude" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."_sync_reservation_occupancy"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."_sync_reservation_occupancy"() TO "service_role";
GRANT ALL ON FUNCTION "public"."_table_free"("p_table_id" "uuid", "p_at" timestamp with time zone, "p_dur_min" integer, "p_buffer" integer, "p_exclude" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."_table_free"("p_table_id" "uuid", "p_at" timestamp with time zone, "p_dur_min" integer, "p_buffer" integer, "p_exclude" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."accept_online_order"("p_online_id" "uuid", "p_staff_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."accept_online_order"("p_online_id" "uuid", "p_staff_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."accept_reservation"("p_id" "uuid", "p_staff_id" "uuid", "p_table_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."accept_reservation"("p_id" "uuid", "p_staff_id" "uuid", "p_table_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."add_cash_movement"("p_shift_id" "uuid", "p_staff_id" "uuid", "p_type" "text", "p_amount" integer, "p_reason" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."add_cash_movement"("p_shift_id" "uuid", "p_staff_id" "uuid", "p_type" "text", "p_amount" integer, "p_reason" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."add_waste"("p_staff_id" "uuid", "p_items" "jsonb", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."add_waste"("p_staff_id" "uuid", "p_items" "jsonb", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."append_to_order"("p_order_id" "uuid", "p_staff_id" "uuid", "p_items" "jsonb", "p_op_uuid" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."append_to_order"("p_order_id" "uuid", "p_staff_id" "uuid", "p_items" "jsonb", "p_op_uuid" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."apply_loyalty"("p_order_id" "uuid", "p_guest_id" "uuid", "p_redeem" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."apply_loyalty"("p_order_id" "uuid", "p_guest_id" "uuid", "p_redeem" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."assert_timesheet_manager"("p_actor_id" "uuid", "p_org" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."assert_timesheet_manager"("p_actor_id" "uuid", "p_org" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."assign_receipt_number"("p_order_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."assign_receipt_number"("p_order_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."auth_location_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."auth_location_id"() TO "service_role";
GRANT ALL ON FUNCTION "public"."auth_org_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."auth_org_id"() TO "service_role";
GRANT ALL ON FUNCTION "public"."bootstrap_org"("p_org_name" "text", "p_location_name" "text", "p_owner_name" "text", "p_owner_pin" "text", "p_business_address" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."bootstrap_org"("p_org_name" "text", "p_location_name" "text", "p_owner_name" "text", "p_owner_pin" "text", "p_business_address" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."cancel_reservation"("p_client_uuid" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."cash_dist"("money", "money") TO "authenticated";
GRANT ALL ON FUNCTION "public"."cash_dist"("money", "money") TO "service_role";
GRANT ALL ON FUNCTION "public"."clamp_client_ts"("p_ts" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."clamp_client_ts"("p_ts" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."clock_in"("p_staff_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."clock_in"("p_staff_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."clock_out"("p_staff_id" "uuid", "p_note" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."clock_out"("p_staff_id" "uuid", "p_note" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."close_shift"("p_shift_id" "uuid", "p_staff_id" "uuid", "p_counted_cash" integer, "p_note" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."close_shift"("p_shift_id" "uuid", "p_staff_id" "uuid", "p_counted_cash" integer, "p_note" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_reservation"("p_location_id" "uuid", "p_staff_id" "uuid", "p_name" "text", "p_phone" "text", "p_party_size" integer, "p_reserved_at" timestamp with time zone, "p_note" "text", "p_table_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_reservation"("p_location_id" "uuid", "p_staff_id" "uuid", "p_name" "text", "p_phone" "text", "p_party_size" integer, "p_reserved_at" timestamp with time zone, "p_note" "text", "p_table_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_staff"("p_name" "text", "p_role" "text", "p_pin" "text", "p_location_id" "uuid", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_staff"("p_name" "text", "p_role" "text", "p_pin" "text", "p_location_id" "uuid", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_table_zone_with_tables"("p_zone_id" "uuid", "p_name" "text", "p_sort_order" integer, "p_table_count" integer, "p_table_prefix" "text", "p_table_sort_order" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_table_zone_with_tables"("p_zone_id" "uuid", "p_name" "text", "p_sort_order" integer, "p_table_count" integer, "p_table_prefix" "text", "p_table_sort_order" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."current_shift"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."current_shift"() TO "service_role";
GRANT ALL ON FUNCTION "public"."date_dist"("date", "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."date_dist"("date", "date") TO "service_role";
GRANT ALL ON FUNCTION "public"."delete_staff"("p_staff_id" "uuid", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_staff"("p_staff_id" "uuid", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."delete_table_zone"("p_zone_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_table_zone"("p_zone_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."delete_time_entry"("p_entry_id" "uuid", "p_actor_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_time_entry"("p_entry_id" "uuid", "p_actor_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."float4_dist"(real, real) TO "authenticated";
GRANT ALL ON FUNCTION "public"."float4_dist"(real, real) TO "service_role";
GRANT ALL ON FUNCTION "public"."float8_dist"(double precision, double precision) TO "authenticated";
GRANT ALL ON FUNCTION "public"."float8_dist"(double precision, double precision) TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bit_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bit_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bit_consistent"("internal", bit, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bit_consistent"("internal", bit, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bit_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bit_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bit_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bit_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bit_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bit_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bit_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bit_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_consistent"("internal", boolean, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_consistent"("internal", boolean, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_same"("public"."gbtreekey2", "public"."gbtreekey2", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_same"("public"."gbtreekey2", "public"."gbtreekey2", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bool_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bool_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bpchar_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bpchar_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bpchar_consistent"("internal", character, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bpchar_consistent"("internal", character, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bytea_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bytea_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bytea_consistent"("internal", "bytea", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bytea_consistent"("internal", "bytea", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bytea_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bytea_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bytea_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bytea_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bytea_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bytea_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_bytea_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_bytea_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_consistent"("internal", "money", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_consistent"("internal", "money", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_distance"("internal", "money", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_distance"("internal", "money", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_cash_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_cash_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_consistent"("internal", "date", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_consistent"("internal", "date", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_distance"("internal", "date", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_distance"("internal", "date", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_date_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_date_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_decompress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_decompress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_consistent"("internal", "anyenum", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_consistent"("internal", "anyenum", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_enum_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_enum_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_consistent"("internal", real, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_consistent"("internal", real, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_distance"("internal", real, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_distance"("internal", real, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float4_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float4_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_consistent"("internal", double precision, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_consistent"("internal", double precision, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_distance"("internal", double precision, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_distance"("internal", double precision, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_float8_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_float8_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_inet_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_inet_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_inet_consistent"("internal", "inet", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_inet_consistent"("internal", "inet", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_inet_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_inet_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_inet_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_inet_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_inet_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_inet_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_inet_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_inet_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_consistent"("internal", smallint, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_consistent"("internal", smallint, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_distance"("internal", smallint, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_distance"("internal", smallint, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_same"("public"."gbtreekey4", "public"."gbtreekey4", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_same"("public"."gbtreekey4", "public"."gbtreekey4", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int2_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int2_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_consistent"("internal", integer, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_consistent"("internal", integer, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_distance"("internal", integer, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_distance"("internal", integer, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int4_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int4_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_consistent"("internal", bigint, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_consistent"("internal", bigint, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_distance"("internal", bigint, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_distance"("internal", bigint, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_int8_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_int8_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_consistent"("internal", interval, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_consistent"("internal", interval, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_decompress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_decompress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_distance"("internal", interval, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_distance"("internal", interval, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_same"("public"."gbtreekey32", "public"."gbtreekey32", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_same"("public"."gbtreekey32", "public"."gbtreekey32", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_intv_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_intv_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_consistent"("internal", "macaddr8", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_consistent"("internal", "macaddr8", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad8_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad8_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_consistent"("internal", "macaddr", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_consistent"("internal", "macaddr", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_macad_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_macad_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_numeric_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_numeric_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_numeric_consistent"("internal", numeric, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_numeric_consistent"("internal", numeric, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_numeric_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_numeric_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_numeric_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_numeric_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_numeric_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_numeric_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_numeric_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_numeric_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_consistent"("internal", "oid", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_consistent"("internal", "oid", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_distance"("internal", "oid", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_distance"("internal", "oid", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_same"("public"."gbtreekey8", "public"."gbtreekey8", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_oid_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_oid_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_text_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_text_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_text_consistent"("internal", "text", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_text_consistent"("internal", "text", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_text_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_text_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_text_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_text_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_text_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_text_same"("public"."gbtreekey_var", "public"."gbtreekey_var", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_text_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_text_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_consistent"("internal", time without time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_consistent"("internal", time without time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_distance"("internal", time without time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_distance"("internal", time without time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_time_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_time_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_timetz_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_timetz_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_timetz_consistent"("internal", time with time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_timetz_consistent"("internal", time with time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_consistent"("internal", timestamp without time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_consistent"("internal", timestamp without time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_distance"("internal", timestamp without time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_distance"("internal", timestamp without time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_same"("public"."gbtreekey16", "public"."gbtreekey16", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_ts_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_ts_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_tstz_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_tstz_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_tstz_consistent"("internal", timestamp with time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_tstz_consistent"("internal", timestamp with time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_tstz_distance"("internal", timestamp with time zone, smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_tstz_distance"("internal", timestamp with time zone, smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_compress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_consistent"("internal", "uuid", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_consistent"("internal", "uuid", smallint, "oid", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_penalty"("internal", "internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_picksplit"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_same"("public"."gbtreekey32", "public"."gbtreekey32", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_same"("public"."gbtreekey32", "public"."gbtreekey32", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_uuid_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_uuid_union"("internal", "internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_var_decompress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_var_decompress"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbt_var_fetch"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbt_var_fetch"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey16_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey16_in"("cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey16_out"("public"."gbtreekey16") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey16_out"("public"."gbtreekey16") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey2_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey2_in"("cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey2_out"("public"."gbtreekey2") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey2_out"("public"."gbtreekey2") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey32_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey32_in"("cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey32_out"("public"."gbtreekey32") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey32_out"("public"."gbtreekey32") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey4_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey4_in"("cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey4_out"("public"."gbtreekey4") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey4_out"("public"."gbtreekey4") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey8_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey8_in"("cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey8_out"("public"."gbtreekey8") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey8_out"("public"."gbtreekey8") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey_var_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey_var_in"("cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."gbtreekey_var_out"("public"."gbtreekey_var") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gbtreekey_var_out"("public"."gbtreekey_var") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_online_order_status"("p_client_uuid" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_reservation_status"("p_client_uuid" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."guest_history"("p_phone" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."guest_history"("p_phone" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."int2_dist"(smallint, smallint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."int2_dist"(smallint, smallint) TO "service_role";
GRANT ALL ON FUNCTION "public"."int4_dist"(integer, integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."int4_dist"(integer, integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."int8_dist"(bigint, bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."int8_dist"(bigint, bigint) TO "service_role";
GRANT ALL ON FUNCTION "public"."interval_dist"(interval, interval) TO "authenticated";
GRANT ALL ON FUNCTION "public"."interval_dist"(interval, interval) TO "service_role";
GRANT ALL ON FUNCTION "public"."issue_refund"("p_refund_id" "uuid", "p_order_id" "uuid", "p_staff_id" "uuid", "p_amount" integer, "p_method" "text", "p_reason" "text", "p_items" "jsonb", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."issue_refund"("p_refund_id" "uuid", "p_order_id" "uuid", "p_staff_id" "uuid", "p_amount" integer, "p_method" "text", "p_reason" "text", "p_items" "jsonb", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."mark_item_ready"("p_item_id" "uuid", "p_ready" boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."mark_item_ready"("p_item_id" "uuid", "p_ready" boolean) TO "service_role";
GRANT ALL ON FUNCTION "public"."mark_order_ready"("p_order_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."mark_order_ready"("p_order_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."merge_table_orders"("p_source_id" "uuid", "p_target_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."merge_table_orders"("p_source_id" "uuid", "p_target_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."move_table_order"("p_order_id" "uuid", "p_to_table_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."move_table_order"("p_order_id" "uuid", "p_to_table_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."oid_dist"("oid", "oid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."oid_dist"("oid", "oid") TO "service_role";
GRANT ALL ON FUNCTION "public"."open_or_get_table_order"("p_table_id" "uuid", "p_staff_id" "uuid", "p_client_uuid" "uuid", "p_opened_at" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."open_or_get_table_order"("p_table_id" "uuid", "p_staff_id" "uuid", "p_client_uuid" "uuid", "p_opened_at" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."open_shift"("p_staff_id" "uuid", "p_opening_float" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."open_shift"("p_staff_id" "uuid", "p_opening_float" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."open_time_entry"("p_staff_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."open_time_entry"("p_staff_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."order_items_stock_qty"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."order_items_stock_qty"() TO "service_role";
GRANT ALL ON FUNCTION "public"."order_items_stock_sale"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."order_items_stock_sale"() TO "service_role";
GRANT ALL ON FUNCTION "public"."order_items_stock_void"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."order_items_stock_void"() TO "service_role";
GRANT ALL ON FUNCTION "public"."orders_stock_void"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."orders_stock_void"() TO "service_role";
GRANT ALL ON FUNCTION "public"."patch_location_settings"("p_patch" "jsonb", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."patch_location_settings"("p_patch" "jsonb", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."pay_order"("p_order_id" "uuid", "p_payments" "jsonb", "p_tip" integer, "p_payment_uuid" "uuid", "p_paid_at" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pay_order"("p_order_id" "uuid", "p_payments" "jsonb", "p_tip" integer, "p_payment_uuid" "uuid", "p_paid_at" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."pay_order_unchecked"("p_order_id" "uuid", "p_payments" "jsonb", "p_tip" integer, "p_payment_uuid" "uuid", "p_paid_at" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."place_order"("p_client_uuid" "uuid", "p_staff_id" "uuid", "p_order_type" "text", "p_customer_name" "text", "p_items" "jsonb", "p_discount" "jsonb", "p_table_label" "text", "p_placed_at" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."place_order"("p_client_uuid" "uuid", "p_staff_id" "uuid", "p_order_type" "text", "p_customer_name" "text", "p_items" "jsonb", "p_discount" "jsonb", "p_table_label" "text", "p_placed_at" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."punch_by_pin"("p_pin" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."punch_by_pin"("p_pin" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."receive_stock"("p_staff_id" "uuid", "p_items" "jsonb", "p_note" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."receive_stock"("p_staff_id" "uuid", "p_items" "jsonb", "p_note" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."refund_order"("p_order_id" "uuid", "p_staff_id" "uuid", "p_reason" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."refund_order"("p_order_id" "uuid", "p_staff_id" "uuid", "p_reason" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."register_device"("p_device_uuid" "uuid", "p_name" "text", "p_settings" "jsonb", "p_app_version" "text", "p_webview_version" "text", "p_printer_capabilities" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."register_device"("p_device_uuid" "uuid", "p_name" "text", "p_settings" "jsonb", "p_app_version" "text", "p_webview_version" "text", "p_printer_capabilities" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."reject_online_order"("p_online_id" "uuid", "p_staff_id" "uuid", "p_reason" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."reject_online_order"("p_online_id" "uuid", "p_staff_id" "uuid", "p_reason" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."reject_reservation"("p_id" "uuid", "p_staff_id" "uuid", "p_reason" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."reject_reservation"("p_id" "uuid", "p_staff_id" "uuid", "p_reason" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."rename_table_zone"("p_zone_id" "uuid", "p_name" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."rename_table_zone"("p_zone_id" "uuid", "p_name" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."reorder_menu"("p_kind" "text", "p_ids" "jsonb", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."reorder_menu"("p_kind" "text", "p_ids" "jsonb", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."reorder_table_zones"("p_zone_ids" "uuid"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."reorder_table_zones"("p_zone_ids" "uuid"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."require_staff_perm"("p_session" "uuid", "p_perm" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."require_staff_perm"("p_session" "uuid", "p_perm" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."reservation_availability"("p_location_id" "uuid", "p_date" "date", "p_party" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."round_order_total"("p_total" integer, "p_pre_cut" integer, "p_has_discount" boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."round_order_total"("p_total" integer, "p_pre_cut" integer, "p_has_discount" boolean) TO "service_role";
GRANT ALL ON FUNCTION "public"."sales_report"("p_from" timestamp with time zone, "p_to" timestamp with time zone, "p_tz" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."sales_report"("p_from" timestamp with time zone, "p_to" timestamp with time zone, "p_tz" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."save_menu_item"("p_item" "jsonb", "p_variants" "jsonb", "p_group_ids" "jsonb", "p_item_id" "uuid", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."save_menu_item"("p_item" "jsonb", "p_variants" "jsonb", "p_group_ids" "jsonb", "p_item_id" "uuid", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."save_time_entry"("p_entry_id" "uuid", "p_staff_id" "uuid", "p_clock_in" timestamp with time zone, "p_clock_out" timestamp with time zone, "p_actor_id" "uuid", "p_note" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."save_time_entry"("p_entry_id" "uuid", "p_staff_id" "uuid", "p_clock_in" timestamp with time zone, "p_clock_out" timestamp with time zone, "p_actor_id" "uuid", "p_note" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."seat_reservation"("p_id" "uuid", "p_staff_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."seat_reservation"("p_id" "uuid", "p_staff_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_online_pause"("p_paused_until" timestamp with time zone, "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_online_pause"("p_paused_until" timestamp with time zone, "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_online_prep_minutes"("p_minutes" integer, "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_online_prep_minutes"("p_minutes" integer, "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_online_prep_range"("p_min" integer, "p_max" integer, "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_online_prep_range"("p_min" integer, "p_max" integer, "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_order_buyer"("p_order_id" "uuid", "p_name" "text", "p_tax_id" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_order_buyer"("p_order_id" "uuid", "p_name" "text", "p_tax_id" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_order_discount"("p_order_id" "uuid", "p_type" "text", "p_value" integer, "p_reason" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_order_discount"("p_order_id" "uuid", "p_type" "text", "p_value" integer, "p_reason" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_order_status"("p_order_id" "uuid", "p_status" "text", "p_reason" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_order_status"("p_order_id" "uuid", "p_status" "text", "p_reason" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_reservation_table"("p_id" "uuid", "p_staff_id" "uuid", "p_table_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_reservation_table"("p_id" "uuid", "p_staff_id" "uuid", "p_table_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_staff_pin"("p_staff_id" "uuid", "p_pin" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_staff_pin"("p_staff_id" "uuid", "p_pin" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_supply_item_active"("p_id" "uuid", "p_active" boolean, "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_supply_item_active"("p_id" "uuid", "p_active" boolean, "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_table_layout"("p_table_id" "uuid", "p_x" numeric, "p_y" numeric, "p_width" numeric, "p_shape" "text", "p_height" numeric) TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_table_layout"("p_table_id" "uuid", "p_x" numeric, "p_y" numeric, "p_width" numeric, "p_shape" "text", "p_height" numeric) TO "service_role";
GRANT ALL ON FUNCTION "public"."set_table_status"("p_table_id" "uuid", "p_status" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_table_status"("p_table_id" "uuid", "p_status" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."shift_report"("p_shift_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."shift_report"("p_shift_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."split_order"("p_order_id" "uuid", "p_staff_id" "uuid", "p_items" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."split_order"("p_order_id" "uuid", "p_staff_id" "uuid", "p_items" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."stock_report"("p_from" timestamp with time zone, "p_to" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."stock_report"("p_from" timestamp with time zone, "p_to" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."stock_take"("p_staff_id" "uuid", "p_items" "jsonb", "p_note" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."stock_take"("p_staff_id" "uuid", "p_items" "jsonb", "p_note" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."submit_online_order"("p_location_id" "uuid", "p_client_uuid" "uuid", "p_name" "text", "p_phone" "text", "p_items" "jsonb", "p_pickup_at" timestamp with time zone, "p_note" "text", "p_order_type" "text", "p_delivery_address" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."submit_reservation"("p_location_id" "uuid", "p_client_uuid" "uuid", "p_name" "text", "p_phone" "text", "p_party_size" integer, "p_reserved_at" timestamp with time zone, "p_note" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."time_dist"(time without time zone, time without time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."time_dist"(time without time zone, time without time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."time_entries_report"("p_from" timestamp with time zone, "p_to" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."time_entries_report"("p_from" timestamp with time zone, "p_to" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."ts_dist"(timestamp without time zone, timestamp without time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."ts_dist"(timestamp without time zone, timestamp without time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."tstz_dist"(timestamp with time zone, timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."tstz_dist"(timestamp with time zone, timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."update_device_settings"("p_device_uuid" "uuid", "p_patch" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_device_settings"("p_device_uuid" "uuid", "p_patch" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."update_location_config"("p_patch" "jsonb", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_location_config"("p_patch" "jsonb", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."update_staff"("p_staff_id" "uuid", "p_patch" "jsonb", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_staff"("p_staff_id" "uuid", "p_patch" "jsonb", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."upsert_supply_item"("p_id" "uuid", "p_name" "text", "p_unit" "text", "p_sku" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."upsert_supply_item"("p_id" "uuid", "p_name" "text", "p_unit" "text", "p_sku" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."verify_staff_pin"("p_pin" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."verify_staff_pin"("p_pin" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."void_order_item"("p_item_id" "uuid", "p_staff_id" "uuid", "p_reason" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."void_order_item"("p_item_id" "uuid", "p_staff_id" "uuid", "p_reason" "text", "p_staff_session" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."void_table_order"("p_order_id" "uuid", "p_reason" "text", "p_staff_session" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."void_table_order"("p_order_id" "uuid", "p_reason" "text", "p_staff_session" "uuid") TO "service_role";

